#!/bin/bash
cd /Users/donghaesamyug/Desktop/Marlin
git fetch origin && git reset --hard origin/experimental
use_example_configs Mieum
cd /Users/donghaesamyug/Desktop/Marlin/Marlin
make -j12 clean
make -j12
#make -j12 upload UPLOAD_PORT=$(listport)